name: Nightly tests (oneC only) — Allure + Pages + Email (smart filter)

on:
  schedule:
    - cron: '0 21 * * *'   # 01:00 Asia/Yerevan (UTC+4) = 21:00 UTC
  workflow_dispatch:

permissions:
  contents: write   # нужно для публикации в gh-pages

jobs:
  test-allure-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 11 (Corretto)
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '11'

      - name: Cache Maven repo
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      # 1) Пытаемся запустить только oneC.*Test
      # 2) Если allure-results пуст, делаем fallback: прогон всех тестов
      - name: Run tests (oneC.*Test with fallback)
        continue-on-error: true
        run: |
          echo ">>> Try filtered run: -Dtest=oneC.*Test"
          mvn -B -e -Dmaven.test.failure.ignore=true -Dtest="oneC.*Test" test || true

          echo ">>> Check Allure results after filtered run"
          if [ ! -d "target/allure-results" ] || [ "$(find target/allure-results -type f | wc -l)" -eq 0 ]; then
            echo ">>> No Allure results found. Fallback: run ALL tests"
            mvn -B -e -Dmaven.test.failure.ignore=true test || true
          else
            echo ">>> Allure results exist after filtered run"
          fi

      - name: Set up Node (for Allure CLI)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Allure CLI
        run: |
          npm i -g allure-commandline@latest
          allure --version

      # Диагностика: убедимся, что результаты есть
      - name: Debug surefire & allure results
        if: always()
        run: |
          echo "===== surefire-reports ====="
          ls -la target/surefire-reports || true
          echo "Total surefire files:" && (find target/surefire-reports -type f | wc -l || true)
          echo
          echo "===== allure-results ====="
          ls -la target/allure-results || true
          echo "Total allure files:" && (find target/allure-results -type f | wc -l || true)

      - name: Generate Allure report (static)
        if: always()
        run: |
          rm -rf allure-report
          allure generate target/allure-results -o allure-report --clean

      - name: Publish Allure to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report

      - name: Upload artifacts (Allure + Surefire)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            target/surefire-reports/**
            target/allure-results/**
            allure-report/**
          retention-days: 14

      - name: Send report by email (links only)
        if: always()
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          from: ${{ secrets.MAIL_FROM }}   # тот же адрес, что и username
          to: ${{ secrets.MAIL_TO }}
          subject: "Nightly oneC: ${{ github.repository }} • ${{ job.status }}"
          html_body: |
            <p>Ночной прогон (oneC.*Test) завершился со статусом: <b>${{ job.status }}</b>.</p>
            <p>Allure отчёт: <a href="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/">открыть</a></p>
            <p>Артефакты рана: <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">скачать</a></p>
