name: Nightly tests (oneC only) — Allure + Email

on:
  schedule:
    - cron: '*/15 * * * *'   # 01:00 по Еревану (UTC+4) = 21:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test-allure-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 11 (Corretto)
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '11'

      - name: Cache Maven repo
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Run only oneC tests
        run: mvn -B -e -Dtest="oneC.*" test

      - name: Set up Node (for Allure CLI)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Allure CLI
        run: npm i -g allure-commandline@latest

      - name: Generate Allure report (static)
        if: always()
        run: |
          rm -rf allure-report
          allure generate target/allure-results -o allure-report --clean
          zip -r allure-report.zip allure-report

      - name: Upload artifacts (Allure + Surefire)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            target/surefire-reports/**
            target/allure-results/**
            allure-report/**
            allure-report.zip
          retention-days: 14

      - name: Send report by email
        if: always()
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: ${{ secrets.MAIL_SERVER }}
          server_port: ${{ secrets.MAIL_PORT }}
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Nightly oneC: ${{ github.repository }} • ${{ job.status }}"
          from: ${{ secrets.MAIL_FROM }}
          to: ${{ secrets.MAIL_TO }}
          html_body: |
            <p>Ночной прогон (oneC.*) завершился со статусом: <b>${{ job.status }}</b>.</p>
            <p>Скачать артефакты: <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">ссылка</a>.</p>
            <p>Во вложении — архив Allure-отчёта.</p>
          attachments: allure-report.zip
