name: Nightly tests (oneC only) — Allure + Pages + Email (no attachments)

on:
  schedule:
    - cron: '0 21 * * *'   # 01:00 Asia/Yerevan (UTC+4) = 21:00 UTC
  workflow_dispatch:

permissions:
  contents: write   # нужно для публикации в gh-pages

jobs:
  test-allure-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 11 (Corretto)
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '11'

      - name: Cache Maven repo
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      # Запускаем только oneC.* и не валим джобу из-за фейлов тестов
      - name: Run only oneC tests
        continue-on-error: true
        run: mvn -B -e -Dmaven.test.failure.ignore=true -Dtest="oneC.*" test

      - name: Set up Node (for Allure CLI)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Allure CLI
        run: |
          npm i -g allure-commandline@latest
          allure --version

      # Диагностика: убедимся, что в results есть файлы
      - name: Debug allure results
        if: always()
        run: |
          echo "Contents of target/allure-results:"
          ls -la target/allure-results || true
          echo "Total files:" && (find target/allure-results -type f | wc -l || true)

      - name: Generate Allure report (static)
        if: always()
        run: |
          rm -rf allure-report
          allure generate target/allure-results -o allure-report --clean

      # Публикация статического отчёта на GitHub Pages (ветка gh-pages)
      - name: Publish Allure to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report

      # Сохраняем артефакты (на всякий случай)
      - name: Upload artifacts (Allure + Surefire)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            target/surefire-reports/**
            target/allure-results/**
            allure-report/**
          retention-days: 14

      # Письмо БЕЗ вложений (Gmail ничего не блокирует)
      - name: Send report by email (links only)
        if: always()
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          from: ${{ secrets.MAIL_FROM }}         # тот же адрес, что и username
          to: ${{ secrets.MAIL_TO }}
          subject: "Nightly oneC: ${{ github.repository }} • ${{ job.status }}"
          html_body: |
            <p>Ночной прогон (oneC.*) завершился со статусом: <b>${{ job.status }}</b>.</p>
            <p>Allure отчёт: <a href="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/">открыть</a></p>
            <p>Артефакты рана: <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">скачать</a></p>
